create table if not exists public.site_analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  session_id text,
  path text not null default '/',
  referrer_host text,
  viewport text not null default 'unknown',
  language text,
  country_code text,
  attribution jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  client_occurred_at timestamptz,
  occurred_at timestamptz not null default now(),
  constraint site_analytics_event_name_length check (char_length(event_name) between 1 and 50),
  constraint site_analytics_viewport check (viewport in ('mobile', 'tablet', 'desktop', 'unknown'))
);

create index if not exists site_analytics_events_occurred_at_idx
  on public.site_analytics_events (occurred_at desc);

create index if not exists site_analytics_events_name_time_idx
  on public.site_analytics_events (event_name, occurred_at desc);

create index if not exists site_analytics_events_session_idx
  on public.site_analytics_events (session_id)
  where session_id is not null;

alter table public.site_analytics_events enable row level security;

comment on table public.site_analytics_events is
  'Privacy-minimized first-party conversion events for qiaobit.com. No email, name, IP, or chat content.';

create or replace view public.site_analytics_daily
with (security_invoker = true)
as
select
  (occurred_at at time zone 'Asia/Shanghai')::date as event_date,
  count(*) filter (where event_name = 'page_view') as page_views,
  count(distinct session_id) filter (where event_name = 'page_view') as unique_sessions,
  count(*) filter (where event_name = 'project_open') as project_opens,
  count(*) filter (where event_name in ('collab_open', 'collab_submit')) as collaboration_actions,
  count(*) filter (where event_name = 'subscription_expand') as subscription_expands,
  count(*) filter (where event_name = 'skill_sample_open') as sample_opens,
  count(*) filter (where event_name = 'checkout_start') as checkout_starts,
  count(*) filter (where event_name = 'checkout_success') as checkout_successes,
  round(
    100.0 * count(*) filter (where event_name = 'checkout_success')
    / nullif(count(distinct session_id) filter (where event_name = 'page_view'), 0),
    2
  ) as session_to_paid_percent
from public.site_analytics_events
group by 1
order by 1 desc;

comment on view public.site_analytics_daily is
  'Daily qiaobit.com acquisition and paid-conversion funnel in Asia/Shanghai time.';
